package com.twei3131.common.model;

import com.jfinal.plugin.activerecord.ActiveRecordPlugin;

/**
 * Generated by JFinal, do not modify this file.
 * <pre>
 * Example:
 * public void configPlugin(Plugins me) {
 *     ActiveRecordPlugin arp = new ActiveRecordPlugin(...);
 *     _MappingKit.mapping(arp);
 *     me.add(arp);
 * }
 * </pre>
 */
public class _MappingKit {

	public static void mapping(ActiveRecordPlugin arp) {
		arp.addMapping("classes", "classId", Classes.class);
		arp.addMapping("department", "departmentId", Department.class);
		arp.addMapping("grade", "gradeId", Grade.class);
		arp.addMapping("group", "id", Group.class);
		// Composite Primary Key order: groupId,subjectId
		arp.addMapping("grouptosubject", "groupId,subjectId", Grouptosubject.class);
		arp.addMapping("instructor", "instructorId", Instructor.class);
		arp.addMapping("signerror", "studentId", Signerror.class);
		arp.addMapping("student", "studentId", Student.class);
		arp.addMapping("subject", "subjectId", Subject.class);
		arp.addMapping("subjectinfo", "subjectInfoId", Subjectinfo.class);
		// Composite Primary Key order: subjectId,teacherId
		arp.addMapping("subjecttoteacher", "subjectId,teacherId", Subjecttoteacher.class);
		// Composite Primary Key order: subjectId,timesId
		arp.addMapping("subjecttotimes", "subjectId,timesId", Subjecttotimes.class);
		arp.addMapping("teacher", "teacherId", Teacher.class);
		// Composite Primary Key order: studentId,teacherId
		arp.addMapping("tempsign", "studentId,teacherId", Tempsign.class);
		arp.addMapping("times", "timesId", Times.class);
	}
}

