package com.twei3131.common.model;

import com.twei3131.common.model.base.BaseClasses;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Classes extends BaseClasses<Classes> {
	public static final Classes dao = new Classes();
}
