package com.twei3131.common.model;

import com.twei3131.common.model.base.BaseDepartment;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Department extends BaseDepartment<Department> {
	public static final Department dao = new Department();
}
