package com.twei3131.common.model;

import com.twei3131.common.model.base.BaseGrade;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Grade extends BaseGrade<Grade> {
	public static final Grade dao = new Grade();
}
