package com.twei3131.common.model;

import com.twei3131.common.model.base.BaseGroup;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Group extends BaseGroup<Group> {
	public static final Group dao = new Group();
}
