package com.twei3131.common.model;

import com.twei3131.common.model.base.BaseGrouptosubject;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Grouptosubject extends BaseGrouptosubject<Grouptosubject> {
	public static final Grouptosubject dao = new Grouptosubject();
}
