package com.twei3131.common.model;

import com.twei3131.common.model.base.BaseInstructor;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Instructor extends BaseInstructor<Instructor> {
	public static final Instructor dao = new Instructor();
}
