package com.twei3131.common.model;

import com.twei3131.common.model.base.BaseSignerror;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Signerror extends BaseSignerror<Signerror> {
	public static final Signerror dao = new Signerror();
}
