package com.twei3131.common.model;

import com.twei3131.common.model.base.BaseSubjectinfo;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Subjectinfo extends BaseSubjectinfo<Subjectinfo> {
	public static final Subjectinfo dao = new Subjectinfo();
}
