package com.twei3131.common.model;

import com.twei3131.common.model.base.BaseSubjecttoteacher;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Subjecttoteacher extends BaseSubjecttoteacher<Subjecttoteacher> {
	public static final Subjecttoteacher dao = new Subjecttoteacher();
}
