package com.twei3131.common.model;

import com.twei3131.common.model.base.BaseSubjecttotimes;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Subjecttotimes extends BaseSubjecttotimes<Subjecttotimes> {
	public static final Subjecttotimes dao = new Subjecttotimes();
}
