package com.twei3131.common.model;

import com.twei3131.common.model.base.BaseTeacher;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Teacher extends BaseTeacher<Teacher> {
	public static final Teacher dao = new Teacher();
}
