package com.twei3131.common.model;

import com.twei3131.common.model.base.BaseTempsign;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Tempsign extends BaseTempsign<Tempsign> {
	public static final Tempsign dao = new Tempsign();
}
