package com.twei3131.common.model;

import com.twei3131.common.model.base.BaseTimes;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Times extends BaseTimes<Times> {
	public static final Times dao = new Times();
}
