package com.twei3131.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseStudent<M extends BaseStudent<M>> extends Model<M> implements IBean {

	public void setStudentId(java.lang.String studentId) {
		set("studentId", studentId);
	}

	public java.lang.String getStudentId() {
		return get("studentId");
	}

	public void setStudentName(java.lang.String studentName) {
		set("studentName", studentName);
	}

	public java.lang.String getStudentName() {
		return get("studentName");
	}

	public void setDepartmentId(java.lang.Integer departmentId) {
		set("departmentId", departmentId);
	}

	public java.lang.Integer getDepartmentId() {
		return get("departmentId");
	}

	public void setClassId(java.lang.Integer classId) {
		set("classId", classId);
	}

	public java.lang.Integer getClassId() {
		return get("classId");
	}

	public void setPassword(java.lang.String password) {
		set("password", password);
	}

	public java.lang.String getPassword() {
		return get("password");
	}

}
