package com.twei3131.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseSubject<M extends BaseSubject<M>> extends Model<M> implements IBean {

	public void setSubjectId(java.lang.String subjectId) {
		set("subjectId", subjectId);
	}

	public java.lang.String getSubjectId() {
		return get("subjectId");
	}

	public void setSubjectName(java.lang.String subjectName) {
		set("subjectName", subjectName);
	}

	public java.lang.String getSubjectName() {
		return get("subjectName");
	}

	public void setClassNumber(java.lang.Integer classNumber) {
		set("classNumber", classNumber);
	}

	public java.lang.Integer getClassNumber() {
		return get("classNumber");
	}

	public void setType(java.lang.String type) {
		set("type", type);
	}

	public java.lang.String getType() {
		return get("type");
	}

}
