package com.twei3131.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseInstructor<M extends BaseInstructor<M>> extends Model<M> implements IBean {

	public void setInstructorId(java.lang.String instructorId) {
		set("instructorId", instructorId);
	}

	public java.lang.String getInstructorId() {
		return get("instructorId");
	}

	public void setInstructorName(java.lang.String instructorName) {
		set("instructorName", instructorName);
	}

	public java.lang.String getInstructorName() {
		return get("instructorName");
	}

	public void setPhoneNumber(java.lang.String phoneNumber) {
		set("phoneNumber", phoneNumber);
	}

	public java.lang.String getPhoneNumber() {
		return get("phoneNumber");
	}

	public void setPassword(java.lang.String password) {
		set("password", password);
	}

	public java.lang.String getPassword() {
		return get("password");
	}

}
