package com.twei3131.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseDepartment<M extends BaseDepartment<M>> extends Model<M> implements IBean {

	public void setDepartmentId(java.lang.String departmentId) {
		set("departmentId", departmentId);
	}

	public java.lang.String getDepartmentId() {
		return get("departmentId");
	}

	public void setDepartmentName(java.lang.String departmentName) {
		set("departmentName", departmentName);
	}

	public java.lang.String getDepartmentName() {
		return get("departmentName");
	}

	public void setDepartmentLeaderId(java.lang.String departmentLeaderId) {
		set("departmentLeaderId", departmentLeaderId);
	}

	public java.lang.String getDepartmentLeaderId() {
		return get("departmentLeaderId");
	}

}
