package com.twei3131.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseSignerror<M extends BaseSignerror<M>> extends Model<M> implements IBean {

	public void setStudentId(java.lang.String studentId) {
		set("studentId", studentId);
	}

	public java.lang.String getStudentId() {
		return get("studentId");
	}

	public void setTeacherId(java.lang.String teacherId) {
		set("teacherId", teacherId);
	}

	public java.lang.String getTeacherId() {
		return get("teacherId");
	}

	public void setSubjectId(java.lang.String subjectId) {
		set("subjectId", subjectId);
	}

	public java.lang.String getSubjectId() {
		return get("subjectId");
	}

	public void setState(java.lang.String state) {
		set("state", state);
	}

	public java.lang.String getState() {
		return get("state");
	}

	public void setAuditState(java.lang.String auditState) {
		set("auditState", auditState);
	}

	public java.lang.String getAuditState() {
		return get("auditState");
	}

	public void setTimes(java.lang.Integer times) {
		set("times", times);
	}

	public java.lang.Integer getTimes() {
		return get("times");
	}

	public void setTime(java.lang.String time) {
		set("time", time);
	}

	public java.lang.String getTime() {
		return get("time");
	}

}
