package com.twei3131.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseTeacher<M extends BaseTeacher<M>> extends Model<M> implements IBean {

	public void setTeacherId(java.lang.String teacherId) {
		set("teacherId", teacherId);
	}

	public java.lang.String getTeacherId() {
		return get("teacherId");
	}

	public void setTeacherName(java.lang.String teacherName) {
		set("teacherName", teacherName);
	}

	public java.lang.String getTeacherName() {
		return get("teacherName");
	}

	public void setDepartmentId(java.lang.String departmentId) {
		set("departmentId", departmentId);
	}

	public java.lang.String getDepartmentId() {
		return get("departmentId");
	}

	public void setPassword(java.lang.String password) {
		set("password", password);
	}

	public java.lang.String getPassword() {
		return get("password");
	}

}
