package com.twei3131.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseClasses<M extends BaseClasses<M>> extends Model<M> implements IBean {

	public void setClassId(java.lang.String classId) {
		set("classId", classId);
	}

	public java.lang.String getClassId() {
		return get("classId");
	}

	public void setDepartmentId(java.lang.String departmentId) {
		set("departmentId", departmentId);
	}

	public java.lang.String getDepartmentId() {
		return get("departmentId");
	}

	public void setGradeId(java.lang.Integer gradeId) {
		set("gradeId", gradeId);
	}

	public java.lang.Integer getGradeId() {
		return get("gradeId");
	}

	public void setInstructorId(java.lang.String instructorId) {
		set("instructorId", instructorId);
	}

	public java.lang.String getInstructorId() {
		return get("instructorId");
	}

	public void setName(java.lang.String name) {
		set("name", name);
	}

	public java.lang.String getName() {
		return get("name");
	}

}
