package com.twei3131.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseSubjecttotimes<M extends BaseSubjecttotimes<M>> extends Model<M> implements IBean {

	public void setSubjectId(java.lang.String subjectId) {
		set("subjectId", subjectId);
	}

	public java.lang.String getSubjectId() {
		return get("subjectId");
	}

	public void setTimesId(java.lang.String timesId) {
		set("timesId", timesId);
	}

	public java.lang.String getTimesId() {
		return get("timesId");
	}

}
