package com.twei3131.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseGrade<M extends BaseGrade<M>> extends Model<M> implements IBean {

	public void setGradeId(java.lang.Integer gradeId) {
		set("gradeId", gradeId);
	}

	public java.lang.Integer getGradeId() {
		return get("gradeId");
	}

	public void setName(java.lang.String name) {
		set("name", name);
	}

	public java.lang.String getName() {
		return get("name");
	}

}
