package com.twei3131.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseTempsign<M extends BaseTempsign<M>> extends Model<M> implements IBean {

	public void setStudentId(java.lang.String studentId) {
		set("studentId", studentId);
	}

	public java.lang.String getStudentId() {
		return get("studentId");
	}

	public void setTeacherId(java.lang.String teacherId) {
		set("teacherId", teacherId);
	}

	public java.lang.String getTeacherId() {
		return get("teacherId");
	}

	public void setSubjectId(java.lang.String subjectId) {
		set("subjectId", subjectId);
	}

	public java.lang.String getSubjectId() {
		return get("subjectId");
	}

	public void setState(java.lang.String state) {
		set("state", state);
	}

	public java.lang.String getState() {
		return get("state");
	}

	public void setScanState(java.lang.String scanState) {
		set("scanState", scanState);
	}

	public java.lang.String getScanState() {
		return get("scanState");
	}

	public void setHostname(java.lang.String hostname) {
		set("hostname", hostname);
	}

	public java.lang.String getHostname() {
		return get("hostname");
	}

}
