package com.twei3131.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseGrouptosubject<M extends BaseGrouptosubject<M>> extends Model<M> implements IBean {

	public void setGroupId(java.lang.String groupId) {
		set("groupId", groupId);
	}

	public java.lang.String getGroupId() {
		return get("groupId");
	}

	public void setSubjectId(java.lang.String subjectId) {
		set("subjectId", subjectId);
	}

	public java.lang.String getSubjectId() {
		return get("subjectId");
	}

}
